version: '3.8'
services:
  db:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  api:
    image: ghandalf02/python-api:latest
    ports:
      - "5050:5050"
    volumes:
      - ./api:/app 

  web:
    image: ghandalf02/nginx-html:latest
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html 
volumes:
  mongo_data:
